[[entries]]
path = "/home/minamulhaq/projects/inam/md/breaktor/breaktor-gaps.md"

[[entries]]
path = "/home/minamulhaq/projects/inam/md/state-machine.md"

[[entries]]
path = "/home/minamulhaq/projects/inam/md/breaktor.md"
